/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as AppAuthedRouteRouteImport } from './routes/app/_authed/route'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppPairRouteImport } from './routes/app/pair'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicClubsIndexRouteImport } from './routes/_public/clubs/index'
import { Route as PublicClubsSlugRouteRouteImport } from './routes/_public/clubs/$slug/route'
import { Route as PublicClubsNewRouteImport } from './routes/_public/clubs/new'
import { Route as PublicDrillsIndexRouteImport } from './routes/_public/drills/index'
import { Route as PublicDrillsDrillIdRouteImport } from './routes/_public/drills/$drillId'
import { Route as PublicLegalAvisoLegalRouteImport } from './routes/_public/legal/aviso-legal'
import { Route as PublicLegalPrivacyRouteImport } from './routes/_public/legal/privacy'
import { Route as PublicLegalTermsRouteImport } from './routes/_public/legal/terms'
import { Route as PublicPlayersIndexRouteImport } from './routes/_public/players/index'
import { Route as PublicPlayersPlayerSlugRouteImport } from './routes/_public/players/$playerSlug'
import { Route as PublicTournamentsIndexRouteImport } from './routes/_public/tournaments/index'
import { Route as PublicTournamentsTournamentIdRouteImport } from './routes/_public/tournaments/$tournamentId'
import { Route as AppClubSlugManifestDotwebmanifestRouteImport } from './routes/app/$clubSlug.manifest[.]webmanifest'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as AppAuthedClubSlugRouteRouteImport } from './routes/app/_authed/$clubSlug/route'
import { Route as AppAuthedOpsRouteImport } from './routes/app/_authed/ops'
import { Route as AppAuthedSelectClubRouteImport } from './routes/app/_authed/select-club'
import { Route as AppAuthedUpdatePasswordRouteImport } from './routes/app/_authed/update-password'
import { Route as AppJoinSlugRouteImport } from './routes/app/join.$slug'
import { Route as PublicClubsSlugIndexRouteImport } from './routes/_public/clubs/$slug/index'
import { Route as PublicClubsSlugGamesRouteImport } from './routes/_public/clubs/$slug/games'
import { Route as PublicClubsSlugInfoRouteImport } from './routes/_public/clubs/$slug/info'
import { Route as PublicClubsSlugPlayersRouteImport } from './routes/_public/clubs/$slug/players'
import { Route as ApiClubsSlugLogoRouteImport } from './routes/api/clubs/$slug/logo'
import { Route as ApiOgClubsSlugRouteImport } from './routes/api/og/clubs/$slug'
import { Route as ApiOgGamesSplatRouteImport } from './routes/api/og/games/$'
import { Route as ApiOgPlayersSplatRouteImport } from './routes/api/og/players/$'
import { Route as ApiOgTournamentsSplatRouteImport } from './routes/api/og/tournaments/$'
import { Route as AppAuthedClubSlugIndexRouteImport } from './routes/app/_authed/$clubSlug/index'
import { Route as AppAuthedClubSlugChallengesRouteImport } from './routes/app/_authed/$clubSlug/challenges'
import { Route as AppAuthedClubSlugClubRouteRouteImport } from './routes/app/_authed/$clubSlug/club/route'
import { Route as AppAuthedClubSlugNightRouteImport } from './routes/app/_authed/$clubSlug/night'
import { Route as AppAuthedClubSlugTodayRouteImport } from './routes/app/_authed/$clubSlug/today'
import { Route as AppAuthedClubSlugTvRouteImport } from './routes/app/_authed/$clubSlug/tv'
import { Route as AppAuthedClubsNoneRouteImport } from './routes/app/_authed/clubs.none'
import { Route as PublicClubsSlugGameGameIdRouteImport } from './routes/_public/clubs/$slug/game/$gameId'
import { Route as AppAuthedClubSlugClubIndexRouteImport } from './routes/app/_authed/$clubSlug/club/index'
import { Route as AppAuthedClubSlugClubMembersRouteImport } from './routes/app/_authed/$clubSlug/club/members'
import { Route as AppAuthedClubSlugClubTablesRouteImport } from './routes/app/_authed/$clubSlug/club/tables'
import { Route as AppAuthedClubSlugDrillsIndexRouteImport } from './routes/app/_authed/$clubSlug/drills/index'
import { Route as AppAuthedClubSlugDrillsNewRouteImport } from './routes/app/_authed/$clubSlug/drills/new'
import { Route as AppAuthedClubSlugGamesIndexRouteImport } from './routes/app/_authed/$clubSlug/games/index'
import { Route as AppAuthedClubSlugGamesNewRouteImport } from './routes/app/_authed/$clubSlug/games/new'
import { Route as AppAuthedClubSlugInvitePrintRouteImport } from './routes/app/_authed/$clubSlug/invite/print'
import { Route as AppAuthedClubSlugLiveLiveIdRouteImport } from './routes/app/_authed/$clubSlug/live/$liveId'
import { Route as AppAuthedClubSlugMeIndexRouteImport } from './routes/app/_authed/$clubSlug/me/index'
import { Route as AppAuthedClubSlugMeSettingsRouteImport } from './routes/app/_authed/$clubSlug/me/settings'
import { Route as AppAuthedClubSlugPlayersIndexRouteImport } from './routes/app/_authed/$clubSlug/players/index'
import { Route as AppAuthedClubSlugRankingIndexRouteImport } from './routes/app/_authed/$clubSlug/ranking/index'
import { Route as AppAuthedClubSlugRankingDailyRouteImport } from './routes/app/_authed/$clubSlug/ranking/daily'
import { Route as AppAuthedClubSlugTablesIndexRouteImport } from './routes/app/_authed/$clubSlug/tables/index'
import { Route as AppAuthedClubSlugTablesTableIdRouteImport } from './routes/app/_authed/$clubSlug/tables/$tableId'
import { Route as AppAuthedClubSlugTournamentsIndexRouteImport } from './routes/app/_authed/$clubSlug/tournaments/index'
import { Route as AppAuthedClubSlugTournamentsTournamentIdRouteImport } from './routes/app/_authed/$clubSlug/tournaments/$tournamentId'
import { Route as AppAuthedClubSlugDrillsDrillIdIndexRouteImport } from './routes/app/_authed/$clubSlug/drills/$drillId/index'
import { Route as AppAuthedClubSlugDrillsDrillIdEditRouteImport } from './routes/app/_authed/$clubSlug/drills/$drillId/edit'
import { Route as AppAuthedClubSlugGamesGameIdIndexRouteImport } from './routes/app/_authed/$clubSlug/games/$gameId/index'
import { Route as AppAuthedClubSlugGamesGameIdEditRouteImport } from './routes/app/_authed/$clubSlug/games/$gameId/edit'
import { Route as AppAuthedClubSlugMeTrainingIndexRouteImport } from './routes/app/_authed/$clubSlug/me/training/index'
import { Route as AppAuthedClubSlugMeTrainingPlanRouteImport } from './routes/app/_authed/$clubSlug/me/training/plan'
import { Route as AppAuthedClubSlugPlayersPlayerIdIndexRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/index'
import { Route as AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/settings'
import { Route as AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/training/index'
import { Route as AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport } from './routes/app/_authed/$clubSlug/players/$playerId/training/plan'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPairRoute = AppPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicClubsIndexRoute = PublicClubsIndexRouteImport.update({
  id: '/clubs/',
  path: '/clubs/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicClubsSlugRouteRoute = PublicClubsSlugRouteRouteImport.update({
  id: '/clubs/$slug',
  path: '/clubs/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicClubsNewRoute = PublicClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDrillsIndexRoute = PublicDrillsIndexRouteImport.update({
  id: '/drills/',
  path: '/drills/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDrillsDrillIdRoute = PublicDrillsDrillIdRouteImport.update({
  id: '/drills/$drillId',
  path: '/drills/$drillId',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLegalAvisoLegalRoute = PublicLegalAvisoLegalRouteImport.update({
  id: '/legal/aviso-legal',
  path: '/legal/aviso-legal',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLegalPrivacyRoute = PublicLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLegalTermsRoute = PublicLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPlayersIndexRoute = PublicPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPlayersPlayerSlugRoute = PublicPlayersPlayerSlugRouteImport.update({
  id: '/players/$playerSlug',
  path: '/players/$playerSlug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTournamentsIndexRoute = PublicTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTournamentsTournamentIdRoute =
  PublicTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const AppClubSlugManifestDotwebmanifestRoute =
  AppClubSlugManifestDotwebmanifestRouteImport.update({
    id: '/$clubSlug/manifest.webmanifest',
    path: '/$clubSlug/manifest.webmanifest',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedClubSlugRouteRoute = AppAuthedClubSlugRouteRouteImport.update({
  id: '/$clubSlug',
  path: '/$clubSlug',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedOpsRoute = AppAuthedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedSelectClubRoute = AppAuthedSelectClubRouteImport.update({
  id: '/select-club',
  path: '/select-club',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedUpdatePasswordRoute = AppAuthedUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppJoinSlugRoute = AppJoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)
const PublicClubsSlugIndexRoute = PublicClubsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicClubsSlugRouteRoute,
} as any)
const PublicClubsSlugGamesRoute = PublicClubsSlugGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => PublicClubsSlugRouteRoute,
} as any)
const PublicClubsSlugInfoRoute = PublicClubsSlugInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => PublicClubsSlugRouteRoute,
} as any)
const PublicClubsSlugPlayersRoute = PublicClubsSlugPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => PublicClubsSlugRouteRoute,
} as any)
const ApiClubsSlugLogoRoute = ApiClubsSlugLogoRouteImport.update({
  id: '/api/clubs/$slug/logo',
  path: '/api/clubs/$slug/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgClubsSlugRoute = ApiOgClubsSlugRouteImport.update({
  id: '/api/og/clubs/$slug',
  path: '/api/og/clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgGamesSplatRoute = ApiOgGamesSplatRouteImport.update({
  id: '/api/og/games/$',
  path: '/api/og/games/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPlayersSplatRoute = ApiOgPlayersSplatRouteImport.update({
  id: '/api/og/players/$',
  path: '/api/og/players/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgTournamentsSplatRoute = ApiOgTournamentsSplatRouteImport.update({
  id: '/api/og/tournaments/$',
  path: '/api/og/tournaments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedClubSlugIndexRoute = AppAuthedClubSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubSlugChallengesRoute =
  AppAuthedClubSlugChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugClubRouteRoute =
  AppAuthedClubSlugClubRouteRouteImport.update({
    id: '/club',
    path: '/club',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugNightRoute = AppAuthedClubSlugNightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubSlugTodayRoute = AppAuthedClubSlugTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubSlugTvRoute = AppAuthedClubSlugTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppAuthedClubSlugRouteRoute,
} as any)
const AppAuthedClubsNoneRoute = AppAuthedClubsNoneRouteImport.update({
  id: '/clubs/none',
  path: '/clubs/none',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const PublicClubsSlugGameGameIdRoute =
  PublicClubsSlugGameGameIdRouteImport.update({
    id: '/game/$gameId',
    path: '/game/$gameId',
    getParentRoute: () => PublicClubsSlugRouteRoute,
  } as any)
const AppAuthedClubSlugClubIndexRoute =
  AppAuthedClubSlugClubIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthedClubSlugClubRouteRoute,
  } as any)
const AppAuthedClubSlugClubMembersRoute =
  AppAuthedClubSlugClubMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AppAuthedClubSlugClubRouteRoute,
  } as any)
const AppAuthedClubSlugClubTablesRoute =
  AppAuthedClubSlugClubTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AppAuthedClubSlugClubRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsIndexRoute =
  AppAuthedClubSlugDrillsIndexRouteImport.update({
    id: '/drills/',
    path: '/drills/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsNewRoute =
  AppAuthedClubSlugDrillsNewRouteImport.update({
    id: '/drills/new',
    path: '/drills/new',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesIndexRoute =
  AppAuthedClubSlugGamesIndexRouteImport.update({
    id: '/games/',
    path: '/games/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesNewRoute =
  AppAuthedClubSlugGamesNewRouteImport.update({
    id: '/games/new',
    path: '/games/new',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugInvitePrintRoute =
  AppAuthedClubSlugInvitePrintRouteImport.update({
    id: '/invite/print',
    path: '/invite/print',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugLiveLiveIdRoute =
  AppAuthedClubSlugLiveLiveIdRouteImport.update({
    id: '/live/$liveId',
    path: '/live/$liveId',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeIndexRoute =
  AppAuthedClubSlugMeIndexRouteImport.update({
    id: '/me/',
    path: '/me/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeSettingsRoute =
  AppAuthedClubSlugMeSettingsRouteImport.update({
    id: '/me/settings',
    path: '/me/settings',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersIndexRoute =
  AppAuthedClubSlugPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugRankingIndexRoute =
  AppAuthedClubSlugRankingIndexRouteImport.update({
    id: '/ranking/',
    path: '/ranking/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugRankingDailyRoute =
  AppAuthedClubSlugRankingDailyRouteImport.update({
    id: '/ranking/daily',
    path: '/ranking/daily',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTablesIndexRoute =
  AppAuthedClubSlugTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTablesTableIdRoute =
  AppAuthedClubSlugTablesTableIdRouteImport.update({
    id: '/tables/$tableId',
    path: '/tables/$tableId',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTournamentsIndexRoute =
  AppAuthedClubSlugTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugTournamentsTournamentIdRoute =
  AppAuthedClubSlugTournamentsTournamentIdRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsDrillIdIndexRoute =
  AppAuthedClubSlugDrillsDrillIdIndexRouteImport.update({
    id: '/drills/$drillId/',
    path: '/drills/$drillId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugDrillsDrillIdEditRoute =
  AppAuthedClubSlugDrillsDrillIdEditRouteImport.update({
    id: '/drills/$drillId/edit',
    path: '/drills/$drillId/edit',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesGameIdIndexRoute =
  AppAuthedClubSlugGamesGameIdIndexRouteImport.update({
    id: '/games/$gameId/',
    path: '/games/$gameId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugGamesGameIdEditRoute =
  AppAuthedClubSlugGamesGameIdEditRouteImport.update({
    id: '/games/$gameId/edit',
    path: '/games/$gameId/edit',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeTrainingIndexRoute =
  AppAuthedClubSlugMeTrainingIndexRouteImport.update({
    id: '/me/training/',
    path: '/me/training/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugMeTrainingPlanRoute =
  AppAuthedClubSlugMeTrainingPlanRouteImport.update({
    id: '/me/training/plan',
    path: '/me/training/plan',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdIndexRoute =
  AppAuthedClubSlugPlayersPlayerIdIndexRouteImport.update({
    id: '/players/$playerId/',
    path: '/players/$playerId/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdSettingsRoute =
  AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport.update({
    id: '/players/$playerId/settings',
    path: '/players/$playerId/settings',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute =
  AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport.update({
    id: '/players/$playerId/training/',
    path: '/players/$playerId/training/',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)
const AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute =
  AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport.update({
    id: '/players/$playerId/training/plan',
    path: '/players/$playerId/training/plan',
    getParentRoute: () => AppAuthedClubSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/pricing': typeof PublicPricingRoute
  '/search': typeof PublicSearchRoute
  '/app/login': typeof AppLoginRoute
  '/app/pair': typeof AppPairRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/clubs/$slug': typeof PublicClubsSlugRouteRouteWithChildren
  '/app/$clubSlug': typeof AppAuthedClubSlugRouteRouteWithChildren
  '/clubs/new': typeof PublicClubsNewRoute
  '/drills/$drillId': typeof PublicDrillsDrillIdRoute
  '/legal/aviso-legal': typeof PublicLegalAvisoLegalRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/legal/terms': typeof PublicLegalTermsRoute
  '/players/$playerSlug': typeof PublicPlayersPlayerSlugRoute
  '/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/app/$clubSlug/manifest.webmanifest': typeof AppClubSlugManifestDotwebmanifestRoute
  '/app/ops': typeof AppAuthedOpsRoute
  '/app/select-club': typeof AppAuthedSelectClubRoute
  '/app/update-password': typeof AppAuthedUpdatePasswordRoute
  '/app/join/$slug': typeof AppJoinSlugRoute
  '/clubs/': typeof PublicClubsIndexRoute
  '/drills/': typeof PublicDrillsIndexRoute
  '/players/': typeof PublicPlayersIndexRoute
  '/tournaments/': typeof PublicTournamentsIndexRoute
  '/app/': typeof AppAuthedIndexRoute
  '/app/$clubSlug/club': typeof AppAuthedClubSlugClubRouteRouteWithChildren
  '/clubs/$slug/games': typeof PublicClubsSlugGamesRoute
  '/clubs/$slug/info': typeof PublicClubsSlugInfoRoute
  '/clubs/$slug/players': typeof PublicClubsSlugPlayersRoute
  '/api/clubs/$slug/logo': typeof ApiClubsSlugLogoRoute
  '/api/og/clubs/$slug': typeof ApiOgClubsSlugRoute
  '/api/og/games/$': typeof ApiOgGamesSplatRoute
  '/api/og/players/$': typeof ApiOgPlayersSplatRoute
  '/api/og/tournaments/$': typeof ApiOgTournamentsSplatRoute
  '/app/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/$clubSlug/night': typeof AppAuthedClubSlugNightRoute
  '/app/$clubSlug/today': typeof AppAuthedClubSlugTodayRoute
  '/app/$clubSlug/tv': typeof AppAuthedClubSlugTvRoute
  '/app/clubs/none': typeof AppAuthedClubsNoneRoute
  '/clubs/$slug/': typeof PublicClubsSlugIndexRoute
  '/app/$clubSlug/': typeof AppAuthedClubSlugIndexRoute
  '/clubs/$slug/game/$gameId': typeof PublicClubsSlugGameGameIdRoute
  '/app/$clubSlug/club/members': typeof AppAuthedClubSlugClubMembersRoute
  '/app/$clubSlug/club/tables': typeof AppAuthedClubSlugClubTablesRoute
  '/app/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/$clubSlug/invite/print': typeof AppAuthedClubSlugInvitePrintRoute
  '/app/$clubSlug/live/$liveId': typeof AppAuthedClubSlugLiveLiveIdRoute
  '/app/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/$clubSlug/tables/$tableId': typeof AppAuthedClubSlugTablesTableIdRoute
  '/app/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/$clubSlug/club/': typeof AppAuthedClubSlugClubIndexRoute
  '/app/$clubSlug/drills/': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/$clubSlug/games/': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/$clubSlug/me/': typeof AppAuthedClubSlugMeIndexRoute
  '/app/$clubSlug/players/': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/$clubSlug/ranking/': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/$clubSlug/tables/': typeof AppAuthedClubSlugTablesIndexRoute
  '/app/$clubSlug/tournaments/': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/$clubSlug/games/$gameId/edit': typeof AppAuthedClubSlugGamesGameIdEditRoute
  '/app/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/$clubSlug/drills/$drillId/': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/$clubSlug/games/$gameId/': typeof AppAuthedClubSlugGamesGameIdIndexRoute
  '/app/$clubSlug/me/training/': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/$clubSlug/players/$playerId/': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/training/': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppAuthedIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/pricing': typeof PublicPricingRoute
  '/search': typeof PublicSearchRoute
  '/app/login': typeof AppLoginRoute
  '/app/pair': typeof AppPairRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof PublicIndexRoute
  '/clubs/new': typeof PublicClubsNewRoute
  '/drills/$drillId': typeof PublicDrillsDrillIdRoute
  '/legal/aviso-legal': typeof PublicLegalAvisoLegalRoute
  '/legal/privacy': typeof PublicLegalPrivacyRoute
  '/legal/terms': typeof PublicLegalTermsRoute
  '/players/$playerSlug': typeof PublicPlayersPlayerSlugRoute
  '/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/app/$clubSlug/manifest.webmanifest': typeof AppClubSlugManifestDotwebmanifestRoute
  '/app/ops': typeof AppAuthedOpsRoute
  '/app/select-club': typeof AppAuthedSelectClubRoute
  '/app/update-password': typeof AppAuthedUpdatePasswordRoute
  '/app/join/$slug': typeof AppJoinSlugRoute
  '/clubs': typeof PublicClubsIndexRoute
  '/drills': typeof PublicDrillsIndexRoute
  '/players': typeof PublicPlayersIndexRoute
  '/tournaments': typeof PublicTournamentsIndexRoute
  '/clubs/$slug/games': typeof PublicClubsSlugGamesRoute
  '/clubs/$slug/info': typeof PublicClubsSlugInfoRoute
  '/clubs/$slug/players': typeof PublicClubsSlugPlayersRoute
  '/api/clubs/$slug/logo': typeof ApiClubsSlugLogoRoute
  '/api/og/clubs/$slug': typeof ApiOgClubsSlugRoute
  '/api/og/games/$': typeof ApiOgGamesSplatRoute
  '/api/og/players/$': typeof ApiOgPlayersSplatRoute
  '/api/og/tournaments/$': typeof ApiOgTournamentsSplatRoute
  '/app/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/$clubSlug/night': typeof AppAuthedClubSlugNightRoute
  '/app/$clubSlug/today': typeof AppAuthedClubSlugTodayRoute
  '/app/$clubSlug/tv': typeof AppAuthedClubSlugTvRoute
  '/app/clubs/none': typeof AppAuthedClubsNoneRoute
  '/clubs/$slug': typeof PublicClubsSlugIndexRoute
  '/app/$clubSlug': typeof AppAuthedClubSlugIndexRoute
  '/clubs/$slug/game/$gameId': typeof PublicClubsSlugGameGameIdRoute
  '/app/$clubSlug/club/members': typeof AppAuthedClubSlugClubMembersRoute
  '/app/$clubSlug/club/tables': typeof AppAuthedClubSlugClubTablesRoute
  '/app/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/$clubSlug/invite/print': typeof AppAuthedClubSlugInvitePrintRoute
  '/app/$clubSlug/live/$liveId': typeof AppAuthedClubSlugLiveLiveIdRoute
  '/app/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/$clubSlug/tables/$tableId': typeof AppAuthedClubSlugTablesTableIdRoute
  '/app/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/$clubSlug/club': typeof AppAuthedClubSlugClubIndexRoute
  '/app/$clubSlug/drills': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/$clubSlug/games': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/$clubSlug/me': typeof AppAuthedClubSlugMeIndexRoute
  '/app/$clubSlug/players': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/$clubSlug/ranking': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/$clubSlug/tables': typeof AppAuthedClubSlugTablesIndexRoute
  '/app/$clubSlug/tournaments': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/$clubSlug/games/$gameId/edit': typeof AppAuthedClubSlugGamesGameIdEditRoute
  '/app/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/$clubSlug/drills/$drillId': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/$clubSlug/games/$gameId': typeof AppAuthedClubSlugGamesGameIdIndexRoute
  '/app/$clubSlug/me/training': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/$clubSlug/players/$playerId': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/$clubSlug/players/$playerId/training': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/search': typeof PublicSearchRoute
  '/app/login': typeof AppLoginRoute
  '/app/pair': typeof AppPairRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/clubs/$slug': typeof PublicClubsSlugRouteRouteWithChildren
  '/app/_authed/$clubSlug': typeof AppAuthedClubSlugRouteRouteWithChildren
  '/_public/clubs/new': typeof PublicClubsNewRoute
  '/_public/drills/$drillId': typeof PublicDrillsDrillIdRoute
  '/_public/legal/aviso-legal': typeof PublicLegalAvisoLegalRoute
  '/_public/legal/privacy': typeof PublicLegalPrivacyRoute
  '/_public/legal/terms': typeof PublicLegalTermsRoute
  '/_public/players/$playerSlug': typeof PublicPlayersPlayerSlugRoute
  '/_public/tournaments/$tournamentId': typeof PublicTournamentsTournamentIdRoute
  '/app/$clubSlug/manifest.webmanifest': typeof AppClubSlugManifestDotwebmanifestRoute
  '/app/_authed/ops': typeof AppAuthedOpsRoute
  '/app/_authed/select-club': typeof AppAuthedSelectClubRoute
  '/app/_authed/update-password': typeof AppAuthedUpdatePasswordRoute
  '/app/join/$slug': typeof AppJoinSlugRoute
  '/_public/clubs/': typeof PublicClubsIndexRoute
  '/_public/drills/': typeof PublicDrillsIndexRoute
  '/_public/players/': typeof PublicPlayersIndexRoute
  '/_public/tournaments/': typeof PublicTournamentsIndexRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/app/_authed/$clubSlug/club': typeof AppAuthedClubSlugClubRouteRouteWithChildren
  '/_public/clubs/$slug/games': typeof PublicClubsSlugGamesRoute
  '/_public/clubs/$slug/info': typeof PublicClubsSlugInfoRoute
  '/_public/clubs/$slug/players': typeof PublicClubsSlugPlayersRoute
  '/api/clubs/$slug/logo': typeof ApiClubsSlugLogoRoute
  '/api/og/clubs/$slug': typeof ApiOgClubsSlugRoute
  '/api/og/games/$': typeof ApiOgGamesSplatRoute
  '/api/og/players/$': typeof ApiOgPlayersSplatRoute
  '/api/og/tournaments/$': typeof ApiOgTournamentsSplatRoute
  '/app/_authed/$clubSlug/challenges': typeof AppAuthedClubSlugChallengesRoute
  '/app/_authed/$clubSlug/night': typeof AppAuthedClubSlugNightRoute
  '/app/_authed/$clubSlug/today': typeof AppAuthedClubSlugTodayRoute
  '/app/_authed/$clubSlug/tv': typeof AppAuthedClubSlugTvRoute
  '/app/_authed/clubs/none': typeof AppAuthedClubsNoneRoute
  '/_public/clubs/$slug/': typeof PublicClubsSlugIndexRoute
  '/app/_authed/$clubSlug/': typeof AppAuthedClubSlugIndexRoute
  '/_public/clubs/$slug/game/$gameId': typeof PublicClubsSlugGameGameIdRoute
  '/app/_authed/$clubSlug/club/members': typeof AppAuthedClubSlugClubMembersRoute
  '/app/_authed/$clubSlug/club/tables': typeof AppAuthedClubSlugClubTablesRoute
  '/app/_authed/$clubSlug/drills/new': typeof AppAuthedClubSlugDrillsNewRoute
  '/app/_authed/$clubSlug/games/new': typeof AppAuthedClubSlugGamesNewRoute
  '/app/_authed/$clubSlug/invite/print': typeof AppAuthedClubSlugInvitePrintRoute
  '/app/_authed/$clubSlug/live/$liveId': typeof AppAuthedClubSlugLiveLiveIdRoute
  '/app/_authed/$clubSlug/me/settings': typeof AppAuthedClubSlugMeSettingsRoute
  '/app/_authed/$clubSlug/ranking/daily': typeof AppAuthedClubSlugRankingDailyRoute
  '/app/_authed/$clubSlug/tables/$tableId': typeof AppAuthedClubSlugTablesTableIdRoute
  '/app/_authed/$clubSlug/tournaments/$tournamentId': typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  '/app/_authed/$clubSlug/club/': typeof AppAuthedClubSlugClubIndexRoute
  '/app/_authed/$clubSlug/drills/': typeof AppAuthedClubSlugDrillsIndexRoute
  '/app/_authed/$clubSlug/games/': typeof AppAuthedClubSlugGamesIndexRoute
  '/app/_authed/$clubSlug/me/': typeof AppAuthedClubSlugMeIndexRoute
  '/app/_authed/$clubSlug/players/': typeof AppAuthedClubSlugPlayersIndexRoute
  '/app/_authed/$clubSlug/ranking/': typeof AppAuthedClubSlugRankingIndexRoute
  '/app/_authed/$clubSlug/tables/': typeof AppAuthedClubSlugTablesIndexRoute
  '/app/_authed/$clubSlug/tournaments/': typeof AppAuthedClubSlugTournamentsIndexRoute
  '/app/_authed/$clubSlug/drills/$drillId/edit': typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  '/app/_authed/$clubSlug/games/$gameId/edit': typeof AppAuthedClubSlugGamesGameIdEditRoute
  '/app/_authed/$clubSlug/me/training/plan': typeof AppAuthedClubSlugMeTrainingPlanRoute
  '/app/_authed/$clubSlug/players/$playerId/settings': typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  '/app/_authed/$clubSlug/drills/$drillId/': typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  '/app/_authed/$clubSlug/games/$gameId/': typeof AppAuthedClubSlugGamesGameIdIndexRoute
  '/app/_authed/$clubSlug/me/training/': typeof AppAuthedClubSlugMeTrainingIndexRoute
  '/app/_authed/$clubSlug/players/$playerId/': typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  '/app/_authed/$clubSlug/players/$playerId/training/plan': typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  '/app/_authed/$clubSlug/players/$playerId/training/': typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/search'
    | '/app/login'
    | '/app/pair'
    | '/auth/callback'
    | '/clubs/$slug'
    | '/app/$clubSlug'
    | '/clubs/new'
    | '/drills/$drillId'
    | '/legal/aviso-legal'
    | '/legal/privacy'
    | '/legal/terms'
    | '/players/$playerSlug'
    | '/tournaments/$tournamentId'
    | '/app/$clubSlug/manifest.webmanifest'
    | '/app/ops'
    | '/app/select-club'
    | '/app/update-password'
    | '/app/join/$slug'
    | '/clubs/'
    | '/drills/'
    | '/players/'
    | '/tournaments/'
    | '/app/'
    | '/app/$clubSlug/club'
    | '/clubs/$slug/games'
    | '/clubs/$slug/info'
    | '/clubs/$slug/players'
    | '/api/clubs/$slug/logo'
    | '/api/og/clubs/$slug'
    | '/api/og/games/$'
    | '/api/og/players/$'
    | '/api/og/tournaments/$'
    | '/app/$clubSlug/challenges'
    | '/app/$clubSlug/night'
    | '/app/$clubSlug/today'
    | '/app/$clubSlug/tv'
    | '/app/clubs/none'
    | '/clubs/$slug/'
    | '/app/$clubSlug/'
    | '/clubs/$slug/game/$gameId'
    | '/app/$clubSlug/club/members'
    | '/app/$clubSlug/club/tables'
    | '/app/$clubSlug/drills/new'
    | '/app/$clubSlug/games/new'
    | '/app/$clubSlug/invite/print'
    | '/app/$clubSlug/live/$liveId'
    | '/app/$clubSlug/me/settings'
    | '/app/$clubSlug/ranking/daily'
    | '/app/$clubSlug/tables/$tableId'
    | '/app/$clubSlug/tournaments/$tournamentId'
    | '/app/$clubSlug/club/'
    | '/app/$clubSlug/drills/'
    | '/app/$clubSlug/games/'
    | '/app/$clubSlug/me/'
    | '/app/$clubSlug/players/'
    | '/app/$clubSlug/ranking/'
    | '/app/$clubSlug/tables/'
    | '/app/$clubSlug/tournaments/'
    | '/app/$clubSlug/drills/$drillId/edit'
    | '/app/$clubSlug/games/$gameId/edit'
    | '/app/$clubSlug/me/training/plan'
    | '/app/$clubSlug/players/$playerId/settings'
    | '/app/$clubSlug/drills/$drillId/'
    | '/app/$clubSlug/games/$gameId/'
    | '/app/$clubSlug/me/training/'
    | '/app/$clubSlug/players/$playerId/'
    | '/app/$clubSlug/players/$playerId/training/plan'
    | '/app/$clubSlug/players/$playerId/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/search'
    | '/app/login'
    | '/app/pair'
    | '/auth/callback'
    | '/'
    | '/clubs/new'
    | '/drills/$drillId'
    | '/legal/aviso-legal'
    | '/legal/privacy'
    | '/legal/terms'
    | '/players/$playerSlug'
    | '/tournaments/$tournamentId'
    | '/app/$clubSlug/manifest.webmanifest'
    | '/app/ops'
    | '/app/select-club'
    | '/app/update-password'
    | '/app/join/$slug'
    | '/clubs'
    | '/drills'
    | '/players'
    | '/tournaments'
    | '/clubs/$slug/games'
    | '/clubs/$slug/info'
    | '/clubs/$slug/players'
    | '/api/clubs/$slug/logo'
    | '/api/og/clubs/$slug'
    | '/api/og/games/$'
    | '/api/og/players/$'
    | '/api/og/tournaments/$'
    | '/app/$clubSlug/challenges'
    | '/app/$clubSlug/night'
    | '/app/$clubSlug/today'
    | '/app/$clubSlug/tv'
    | '/app/clubs/none'
    | '/clubs/$slug'
    | '/app/$clubSlug'
    | '/clubs/$slug/game/$gameId'
    | '/app/$clubSlug/club/members'
    | '/app/$clubSlug/club/tables'
    | '/app/$clubSlug/drills/new'
    | '/app/$clubSlug/games/new'
    | '/app/$clubSlug/invite/print'
    | '/app/$clubSlug/live/$liveId'
    | '/app/$clubSlug/me/settings'
    | '/app/$clubSlug/ranking/daily'
    | '/app/$clubSlug/tables/$tableId'
    | '/app/$clubSlug/tournaments/$tournamentId'
    | '/app/$clubSlug/club'
    | '/app/$clubSlug/drills'
    | '/app/$clubSlug/games'
    | '/app/$clubSlug/me'
    | '/app/$clubSlug/players'
    | '/app/$clubSlug/ranking'
    | '/app/$clubSlug/tables'
    | '/app/$clubSlug/tournaments'
    | '/app/$clubSlug/drills/$drillId/edit'
    | '/app/$clubSlug/games/$gameId/edit'
    | '/app/$clubSlug/me/training/plan'
    | '/app/$clubSlug/players/$playerId/settings'
    | '/app/$clubSlug/drills/$drillId'
    | '/app/$clubSlug/games/$gameId'
    | '/app/$clubSlug/me/training'
    | '/app/$clubSlug/players/$playerId'
    | '/app/$clubSlug/players/$playerId/training/plan'
    | '/app/$clubSlug/players/$playerId/training'
  id:
    | '__root__'
    | '/_public'
    | '/app'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/app/_authed'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/pricing'
    | '/_public/search'
    | '/app/login'
    | '/app/pair'
    | '/auth/callback'
    | '/_public/'
    | '/_public/clubs/$slug'
    | '/app/_authed/$clubSlug'
    | '/_public/clubs/new'
    | '/_public/drills/$drillId'
    | '/_public/legal/aviso-legal'
    | '/_public/legal/privacy'
    | '/_public/legal/terms'
    | '/_public/players/$playerSlug'
    | '/_public/tournaments/$tournamentId'
    | '/app/$clubSlug/manifest.webmanifest'
    | '/app/_authed/ops'
    | '/app/_authed/select-club'
    | '/app/_authed/update-password'
    | '/app/join/$slug'
    | '/_public/clubs/'
    | '/_public/drills/'
    | '/_public/players/'
    | '/_public/tournaments/'
    | '/app/_authed/'
    | '/app/_authed/$clubSlug/club'
    | '/_public/clubs/$slug/games'
    | '/_public/clubs/$slug/info'
    | '/_public/clubs/$slug/players'
    | '/api/clubs/$slug/logo'
    | '/api/og/clubs/$slug'
    | '/api/og/games/$'
    | '/api/og/players/$'
    | '/api/og/tournaments/$'
    | '/app/_authed/$clubSlug/challenges'
    | '/app/_authed/$clubSlug/night'
    | '/app/_authed/$clubSlug/today'
    | '/app/_authed/$clubSlug/tv'
    | '/app/_authed/clubs/none'
    | '/_public/clubs/$slug/'
    | '/app/_authed/$clubSlug/'
    | '/_public/clubs/$slug/game/$gameId'
    | '/app/_authed/$clubSlug/club/members'
    | '/app/_authed/$clubSlug/club/tables'
    | '/app/_authed/$clubSlug/drills/new'
    | '/app/_authed/$clubSlug/games/new'
    | '/app/_authed/$clubSlug/invite/print'
    | '/app/_authed/$clubSlug/live/$liveId'
    | '/app/_authed/$clubSlug/me/settings'
    | '/app/_authed/$clubSlug/ranking/daily'
    | '/app/_authed/$clubSlug/tables/$tableId'
    | '/app/_authed/$clubSlug/tournaments/$tournamentId'
    | '/app/_authed/$clubSlug/club/'
    | '/app/_authed/$clubSlug/drills/'
    | '/app/_authed/$clubSlug/games/'
    | '/app/_authed/$clubSlug/me/'
    | '/app/_authed/$clubSlug/players/'
    | '/app/_authed/$clubSlug/ranking/'
    | '/app/_authed/$clubSlug/tables/'
    | '/app/_authed/$clubSlug/tournaments/'
    | '/app/_authed/$clubSlug/drills/$drillId/edit'
    | '/app/_authed/$clubSlug/games/$gameId/edit'
    | '/app/_authed/$clubSlug/me/training/plan'
    | '/app/_authed/$clubSlug/players/$playerId/settings'
    | '/app/_authed/$clubSlug/drills/$drillId/'
    | '/app/_authed/$clubSlug/games/$gameId/'
    | '/app/_authed/$clubSlug/me/training/'
    | '/app/_authed/$clubSlug/players/$playerId/'
    | '/app/_authed/$clubSlug/players/$playerId/training/plan'
    | '/app/_authed/$clubSlug/players/$playerId/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiClubsSlugLogoRoute: typeof ApiClubsSlugLogoRoute
  ApiOgClubsSlugRoute: typeof ApiOgClubsSlugRoute
  ApiOgGamesSplatRoute: typeof ApiOgGamesSplatRoute
  ApiOgPlayersSplatRoute: typeof ApiOgPlayersSplatRoute
  ApiOgTournamentsSplatRoute: typeof ApiOgTournamentsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pair': {
      id: '/app/pair'
      path: '/pair'
      fullPath: '/app/pair'
      preLoaderRoute: typeof AppPairRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/clubs/': {
      id: '/_public/clubs/'
      path: '/clubs'
      fullPath: '/clubs/'
      preLoaderRoute: typeof PublicClubsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/clubs/$slug': {
      id: '/_public/clubs/$slug'
      path: '/clubs/$slug'
      fullPath: '/clubs/$slug'
      preLoaderRoute: typeof PublicClubsSlugRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/clubs/new': {
      id: '/_public/clubs/new'
      path: '/clubs/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof PublicClubsNewRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/drills/': {
      id: '/_public/drills/'
      path: '/drills'
      fullPath: '/drills/'
      preLoaderRoute: typeof PublicDrillsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/drills/$drillId': {
      id: '/_public/drills/$drillId'
      path: '/drills/$drillId'
      fullPath: '/drills/$drillId'
      preLoaderRoute: typeof PublicDrillsDrillIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal/aviso-legal': {
      id: '/_public/legal/aviso-legal'
      path: '/legal/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof PublicLegalAvisoLegalRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal/privacy': {
      id: '/_public/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof PublicLegalPrivacyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/legal/terms': {
      id: '/_public/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof PublicLegalTermsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/players/': {
      id: '/_public/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PublicPlayersIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/players/$playerSlug': {
      id: '/_public/players/$playerSlug'
      path: '/players/$playerSlug'
      fullPath: '/players/$playerSlug'
      preLoaderRoute: typeof PublicPlayersPlayerSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/tournaments/': {
      id: '/_public/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof PublicTournamentsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/tournaments/$tournamentId': {
      id: '/_public/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof PublicTournamentsTournamentIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/app/$clubSlug/manifest.webmanifest': {
      id: '/app/$clubSlug/manifest.webmanifest'
      path: '/$clubSlug/manifest.webmanifest'
      fullPath: '/app/$clubSlug/manifest.webmanifest'
      preLoaderRoute: typeof AppClubSlugManifestDotwebmanifestRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/$clubSlug': {
      id: '/app/_authed/$clubSlug'
      path: '/$clubSlug'
      fullPath: '/app/$clubSlug'
      preLoaderRoute: typeof AppAuthedClubSlugRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/ops': {
      id: '/app/_authed/ops'
      path: '/ops'
      fullPath: '/app/ops'
      preLoaderRoute: typeof AppAuthedOpsRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/select-club': {
      id: '/app/_authed/select-club'
      path: '/select-club'
      fullPath: '/app/select-club'
      preLoaderRoute: typeof AppAuthedSelectClubRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/update-password': {
      id: '/app/_authed/update-password'
      path: '/update-password'
      fullPath: '/app/update-password'
      preLoaderRoute: typeof AppAuthedUpdatePasswordRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/join/$slug': {
      id: '/app/join/$slug'
      path: '/join/$slug'
      fullPath: '/app/join/$slug'
      preLoaderRoute: typeof AppJoinSlugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_public/clubs/$slug/': {
      id: '/_public/clubs/$slug/'
      path: '/'
      fullPath: '/clubs/$slug/'
      preLoaderRoute: typeof PublicClubsSlugIndexRouteImport
      parentRoute: typeof PublicClubsSlugRouteRoute
    }
    '/_public/clubs/$slug/games': {
      id: '/_public/clubs/$slug/games'
      path: '/games'
      fullPath: '/clubs/$slug/games'
      preLoaderRoute: typeof PublicClubsSlugGamesRouteImport
      parentRoute: typeof PublicClubsSlugRouteRoute
    }
    '/_public/clubs/$slug/info': {
      id: '/_public/clubs/$slug/info'
      path: '/info'
      fullPath: '/clubs/$slug/info'
      preLoaderRoute: typeof PublicClubsSlugInfoRouteImport
      parentRoute: typeof PublicClubsSlugRouteRoute
    }
    '/_public/clubs/$slug/players': {
      id: '/_public/clubs/$slug/players'
      path: '/players'
      fullPath: '/clubs/$slug/players'
      preLoaderRoute: typeof PublicClubsSlugPlayersRouteImport
      parentRoute: typeof PublicClubsSlugRouteRoute
    }
    '/api/clubs/$slug/logo': {
      id: '/api/clubs/$slug/logo'
      path: '/api/clubs/$slug/logo'
      fullPath: '/api/clubs/$slug/logo'
      preLoaderRoute: typeof ApiClubsSlugLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/clubs/$slug': {
      id: '/api/og/clubs/$slug'
      path: '/api/og/clubs/$slug'
      fullPath: '/api/og/clubs/$slug'
      preLoaderRoute: typeof ApiOgClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/games/$': {
      id: '/api/og/games/$'
      path: '/api/og/games/$'
      fullPath: '/api/og/games/$'
      preLoaderRoute: typeof ApiOgGamesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/players/$': {
      id: '/api/og/players/$'
      path: '/api/og/players/$'
      fullPath: '/api/og/players/$'
      preLoaderRoute: typeof ApiOgPlayersSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/tournaments/$': {
      id: '/api/og/tournaments/$'
      path: '/api/og/tournaments/$'
      fullPath: '/api/og/tournaments/$'
      preLoaderRoute: typeof ApiOgTournamentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed/$clubSlug/': {
      id: '/app/_authed/$clubSlug/'
      path: '/'
      fullPath: '/app/$clubSlug/'
      preLoaderRoute: typeof AppAuthedClubSlugIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/challenges': {
      id: '/app/_authed/$clubSlug/challenges'
      path: '/challenges'
      fullPath: '/app/$clubSlug/challenges'
      preLoaderRoute: typeof AppAuthedClubSlugChallengesRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/club': {
      id: '/app/_authed/$clubSlug/club'
      path: '/club'
      fullPath: '/app/$clubSlug/club'
      preLoaderRoute: typeof AppAuthedClubSlugClubRouteRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/night': {
      id: '/app/_authed/$clubSlug/night'
      path: '/night'
      fullPath: '/app/$clubSlug/night'
      preLoaderRoute: typeof AppAuthedClubSlugNightRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/today': {
      id: '/app/_authed/$clubSlug/today'
      path: '/today'
      fullPath: '/app/$clubSlug/today'
      preLoaderRoute: typeof AppAuthedClubSlugTodayRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tv': {
      id: '/app/_authed/$clubSlug/tv'
      path: '/tv'
      fullPath: '/app/$clubSlug/tv'
      preLoaderRoute: typeof AppAuthedClubSlugTvRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/clubs/none': {
      id: '/app/_authed/clubs/none'
      path: '/clubs/none'
      fullPath: '/app/clubs/none'
      preLoaderRoute: typeof AppAuthedClubsNoneRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/_public/clubs/$slug/game/$gameId': {
      id: '/_public/clubs/$slug/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/clubs/$slug/game/$gameId'
      preLoaderRoute: typeof PublicClubsSlugGameGameIdRouteImport
      parentRoute: typeof PublicClubsSlugRouteRoute
    }
    '/app/_authed/$clubSlug/club/': {
      id: '/app/_authed/$clubSlug/club/'
      path: '/'
      fullPath: '/app/$clubSlug/club/'
      preLoaderRoute: typeof AppAuthedClubSlugClubIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugClubRouteRoute
    }
    '/app/_authed/$clubSlug/club/members': {
      id: '/app/_authed/$clubSlug/club/members'
      path: '/members'
      fullPath: '/app/$clubSlug/club/members'
      preLoaderRoute: typeof AppAuthedClubSlugClubMembersRouteImport
      parentRoute: typeof AppAuthedClubSlugClubRouteRoute
    }
    '/app/_authed/$clubSlug/club/tables': {
      id: '/app/_authed/$clubSlug/club/tables'
      path: '/tables'
      fullPath: '/app/$clubSlug/club/tables'
      preLoaderRoute: typeof AppAuthedClubSlugClubTablesRouteImport
      parentRoute: typeof AppAuthedClubSlugClubRouteRoute
    }
    '/app/_authed/$clubSlug/drills/': {
      id: '/app/_authed/$clubSlug/drills/'
      path: '/drills'
      fullPath: '/app/$clubSlug/drills/'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/new': {
      id: '/app/_authed/$clubSlug/drills/new'
      path: '/drills/new'
      fullPath: '/app/$clubSlug/drills/new'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsNewRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/': {
      id: '/app/_authed/$clubSlug/games/'
      path: '/games'
      fullPath: '/app/$clubSlug/games/'
      preLoaderRoute: typeof AppAuthedClubSlugGamesIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/new': {
      id: '/app/_authed/$clubSlug/games/new'
      path: '/games/new'
      fullPath: '/app/$clubSlug/games/new'
      preLoaderRoute: typeof AppAuthedClubSlugGamesNewRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/invite/print': {
      id: '/app/_authed/$clubSlug/invite/print'
      path: '/invite/print'
      fullPath: '/app/$clubSlug/invite/print'
      preLoaderRoute: typeof AppAuthedClubSlugInvitePrintRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/live/$liveId': {
      id: '/app/_authed/$clubSlug/live/$liveId'
      path: '/live/$liveId'
      fullPath: '/app/$clubSlug/live/$liveId'
      preLoaderRoute: typeof AppAuthedClubSlugLiveLiveIdRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/': {
      id: '/app/_authed/$clubSlug/me/'
      path: '/me'
      fullPath: '/app/$clubSlug/me/'
      preLoaderRoute: typeof AppAuthedClubSlugMeIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/settings': {
      id: '/app/_authed/$clubSlug/me/settings'
      path: '/me/settings'
      fullPath: '/app/$clubSlug/me/settings'
      preLoaderRoute: typeof AppAuthedClubSlugMeSettingsRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/': {
      id: '/app/_authed/$clubSlug/players/'
      path: '/players'
      fullPath: '/app/$clubSlug/players/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/ranking/': {
      id: '/app/_authed/$clubSlug/ranking/'
      path: '/ranking'
      fullPath: '/app/$clubSlug/ranking/'
      preLoaderRoute: typeof AppAuthedClubSlugRankingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/ranking/daily': {
      id: '/app/_authed/$clubSlug/ranking/daily'
      path: '/ranking/daily'
      fullPath: '/app/$clubSlug/ranking/daily'
      preLoaderRoute: typeof AppAuthedClubSlugRankingDailyRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tables/': {
      id: '/app/_authed/$clubSlug/tables/'
      path: '/tables'
      fullPath: '/app/$clubSlug/tables/'
      preLoaderRoute: typeof AppAuthedClubSlugTablesIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tables/$tableId': {
      id: '/app/_authed/$clubSlug/tables/$tableId'
      path: '/tables/$tableId'
      fullPath: '/app/$clubSlug/tables/$tableId'
      preLoaderRoute: typeof AppAuthedClubSlugTablesTableIdRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tournaments/': {
      id: '/app/_authed/$clubSlug/tournaments/'
      path: '/tournaments'
      fullPath: '/app/$clubSlug/tournaments/'
      preLoaderRoute: typeof AppAuthedClubSlugTournamentsIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/tournaments/$tournamentId': {
      id: '/app/_authed/$clubSlug/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/app/$clubSlug/tournaments/$tournamentId'
      preLoaderRoute: typeof AppAuthedClubSlugTournamentsTournamentIdRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/$drillId/': {
      id: '/app/_authed/$clubSlug/drills/$drillId/'
      path: '/drills/$drillId'
      fullPath: '/app/$clubSlug/drills/$drillId/'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsDrillIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/drills/$drillId/edit': {
      id: '/app/_authed/$clubSlug/drills/$drillId/edit'
      path: '/drills/$drillId/edit'
      fullPath: '/app/$clubSlug/drills/$drillId/edit'
      preLoaderRoute: typeof AppAuthedClubSlugDrillsDrillIdEditRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/$gameId/': {
      id: '/app/_authed/$clubSlug/games/$gameId/'
      path: '/games/$gameId'
      fullPath: '/app/$clubSlug/games/$gameId/'
      preLoaderRoute: typeof AppAuthedClubSlugGamesGameIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/games/$gameId/edit': {
      id: '/app/_authed/$clubSlug/games/$gameId/edit'
      path: '/games/$gameId/edit'
      fullPath: '/app/$clubSlug/games/$gameId/edit'
      preLoaderRoute: typeof AppAuthedClubSlugGamesGameIdEditRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/training/': {
      id: '/app/_authed/$clubSlug/me/training/'
      path: '/me/training'
      fullPath: '/app/$clubSlug/me/training/'
      preLoaderRoute: typeof AppAuthedClubSlugMeTrainingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/me/training/plan': {
      id: '/app/_authed/$clubSlug/me/training/plan'
      path: '/me/training/plan'
      fullPath: '/app/$clubSlug/me/training/plan'
      preLoaderRoute: typeof AppAuthedClubSlugMeTrainingPlanRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/': {
      id: '/app/_authed/$clubSlug/players/$playerId/'
      path: '/players/$playerId'
      fullPath: '/app/$clubSlug/players/$playerId/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/settings': {
      id: '/app/_authed/$clubSlug/players/$playerId/settings'
      path: '/players/$playerId/settings'
      fullPath: '/app/$clubSlug/players/$playerId/settings'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdSettingsRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/training/': {
      id: '/app/_authed/$clubSlug/players/$playerId/training/'
      path: '/players/$playerId/training'
      fullPath: '/app/$clubSlug/players/$playerId/training/'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
    '/app/_authed/$clubSlug/players/$playerId/training/plan': {
      id: '/app/_authed/$clubSlug/players/$playerId/training/plan'
      path: '/players/$playerId/training/plan'
      fullPath: '/app/$clubSlug/players/$playerId/training/plan'
      preLoaderRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRouteImport
      parentRoute: typeof AppAuthedClubSlugRouteRoute
    }
  }
}

interface PublicClubsSlugRouteRouteChildren {
  PublicClubsSlugGamesRoute: typeof PublicClubsSlugGamesRoute
  PublicClubsSlugInfoRoute: typeof PublicClubsSlugInfoRoute
  PublicClubsSlugPlayersRoute: typeof PublicClubsSlugPlayersRoute
  PublicClubsSlugIndexRoute: typeof PublicClubsSlugIndexRoute
  PublicClubsSlugGameGameIdRoute: typeof PublicClubsSlugGameGameIdRoute
}

const PublicClubsSlugRouteRouteChildren: PublicClubsSlugRouteRouteChildren = {
  PublicClubsSlugGamesRoute: PublicClubsSlugGamesRoute,
  PublicClubsSlugInfoRoute: PublicClubsSlugInfoRoute,
  PublicClubsSlugPlayersRoute: PublicClubsSlugPlayersRoute,
  PublicClubsSlugIndexRoute: PublicClubsSlugIndexRoute,
  PublicClubsSlugGameGameIdRoute: PublicClubsSlugGameGameIdRoute,
}

const PublicClubsSlugRouteRouteWithChildren =
  PublicClubsSlugRouteRoute._addFileChildren(PublicClubsSlugRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicClubsSlugRouteRoute: typeof PublicClubsSlugRouteRouteWithChildren
  PublicClubsNewRoute: typeof PublicClubsNewRoute
  PublicDrillsDrillIdRoute: typeof PublicDrillsDrillIdRoute
  PublicLegalAvisoLegalRoute: typeof PublicLegalAvisoLegalRoute
  PublicLegalPrivacyRoute: typeof PublicLegalPrivacyRoute
  PublicLegalTermsRoute: typeof PublicLegalTermsRoute
  PublicPlayersPlayerSlugRoute: typeof PublicPlayersPlayerSlugRoute
  PublicTournamentsTournamentIdRoute: typeof PublicTournamentsTournamentIdRoute
  PublicClubsIndexRoute: typeof PublicClubsIndexRoute
  PublicDrillsIndexRoute: typeof PublicDrillsIndexRoute
  PublicPlayersIndexRoute: typeof PublicPlayersIndexRoute
  PublicTournamentsIndexRoute: typeof PublicTournamentsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicClubsSlugRouteRoute: PublicClubsSlugRouteRouteWithChildren,
  PublicClubsNewRoute: PublicClubsNewRoute,
  PublicDrillsDrillIdRoute: PublicDrillsDrillIdRoute,
  PublicLegalAvisoLegalRoute: PublicLegalAvisoLegalRoute,
  PublicLegalPrivacyRoute: PublicLegalPrivacyRoute,
  PublicLegalTermsRoute: PublicLegalTermsRoute,
  PublicPlayersPlayerSlugRoute: PublicPlayersPlayerSlugRoute,
  PublicTournamentsTournamentIdRoute: PublicTournamentsTournamentIdRoute,
  PublicClubsIndexRoute: PublicClubsIndexRoute,
  PublicDrillsIndexRoute: PublicDrillsIndexRoute,
  PublicPlayersIndexRoute: PublicPlayersIndexRoute,
  PublicTournamentsIndexRoute: PublicTournamentsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AppAuthedClubSlugClubRouteRouteChildren {
  AppAuthedClubSlugClubMembersRoute: typeof AppAuthedClubSlugClubMembersRoute
  AppAuthedClubSlugClubTablesRoute: typeof AppAuthedClubSlugClubTablesRoute
  AppAuthedClubSlugClubIndexRoute: typeof AppAuthedClubSlugClubIndexRoute
}

const AppAuthedClubSlugClubRouteRouteChildren: AppAuthedClubSlugClubRouteRouteChildren =
  {
    AppAuthedClubSlugClubMembersRoute: AppAuthedClubSlugClubMembersRoute,
    AppAuthedClubSlugClubTablesRoute: AppAuthedClubSlugClubTablesRoute,
    AppAuthedClubSlugClubIndexRoute: AppAuthedClubSlugClubIndexRoute,
  }

const AppAuthedClubSlugClubRouteRouteWithChildren =
  AppAuthedClubSlugClubRouteRoute._addFileChildren(
    AppAuthedClubSlugClubRouteRouteChildren,
  )

interface AppAuthedClubSlugRouteRouteChildren {
  AppAuthedClubSlugClubRouteRoute: typeof AppAuthedClubSlugClubRouteRouteWithChildren
  AppAuthedClubSlugChallengesRoute: typeof AppAuthedClubSlugChallengesRoute
  AppAuthedClubSlugNightRoute: typeof AppAuthedClubSlugNightRoute
  AppAuthedClubSlugTodayRoute: typeof AppAuthedClubSlugTodayRoute
  AppAuthedClubSlugTvRoute: typeof AppAuthedClubSlugTvRoute
  AppAuthedClubSlugIndexRoute: typeof AppAuthedClubSlugIndexRoute
  AppAuthedClubSlugDrillsNewRoute: typeof AppAuthedClubSlugDrillsNewRoute
  AppAuthedClubSlugGamesNewRoute: typeof AppAuthedClubSlugGamesNewRoute
  AppAuthedClubSlugInvitePrintRoute: typeof AppAuthedClubSlugInvitePrintRoute
  AppAuthedClubSlugLiveLiveIdRoute: typeof AppAuthedClubSlugLiveLiveIdRoute
  AppAuthedClubSlugMeSettingsRoute: typeof AppAuthedClubSlugMeSettingsRoute
  AppAuthedClubSlugRankingDailyRoute: typeof AppAuthedClubSlugRankingDailyRoute
  AppAuthedClubSlugTablesTableIdRoute: typeof AppAuthedClubSlugTablesTableIdRoute
  AppAuthedClubSlugTournamentsTournamentIdRoute: typeof AppAuthedClubSlugTournamentsTournamentIdRoute
  AppAuthedClubSlugDrillsIndexRoute: typeof AppAuthedClubSlugDrillsIndexRoute
  AppAuthedClubSlugGamesIndexRoute: typeof AppAuthedClubSlugGamesIndexRoute
  AppAuthedClubSlugMeIndexRoute: typeof AppAuthedClubSlugMeIndexRoute
  AppAuthedClubSlugPlayersIndexRoute: typeof AppAuthedClubSlugPlayersIndexRoute
  AppAuthedClubSlugRankingIndexRoute: typeof AppAuthedClubSlugRankingIndexRoute
  AppAuthedClubSlugTablesIndexRoute: typeof AppAuthedClubSlugTablesIndexRoute
  AppAuthedClubSlugTournamentsIndexRoute: typeof AppAuthedClubSlugTournamentsIndexRoute
  AppAuthedClubSlugDrillsDrillIdEditRoute: typeof AppAuthedClubSlugDrillsDrillIdEditRoute
  AppAuthedClubSlugGamesGameIdEditRoute: typeof AppAuthedClubSlugGamesGameIdEditRoute
  AppAuthedClubSlugMeTrainingPlanRoute: typeof AppAuthedClubSlugMeTrainingPlanRoute
  AppAuthedClubSlugPlayersPlayerIdSettingsRoute: typeof AppAuthedClubSlugPlayersPlayerIdSettingsRoute
  AppAuthedClubSlugDrillsDrillIdIndexRoute: typeof AppAuthedClubSlugDrillsDrillIdIndexRoute
  AppAuthedClubSlugGamesGameIdIndexRoute: typeof AppAuthedClubSlugGamesGameIdIndexRoute
  AppAuthedClubSlugMeTrainingIndexRoute: typeof AppAuthedClubSlugMeTrainingIndexRoute
  AppAuthedClubSlugPlayersPlayerIdIndexRoute: typeof AppAuthedClubSlugPlayersPlayerIdIndexRoute
  AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute
  AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute: typeof AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute
}

const AppAuthedClubSlugRouteRouteChildren: AppAuthedClubSlugRouteRouteChildren =
  {
    AppAuthedClubSlugClubRouteRoute:
      AppAuthedClubSlugClubRouteRouteWithChildren,
    AppAuthedClubSlugChallengesRoute: AppAuthedClubSlugChallengesRoute,
    AppAuthedClubSlugNightRoute: AppAuthedClubSlugNightRoute,
    AppAuthedClubSlugTodayRoute: AppAuthedClubSlugTodayRoute,
    AppAuthedClubSlugTvRoute: AppAuthedClubSlugTvRoute,
    AppAuthedClubSlugIndexRoute: AppAuthedClubSlugIndexRoute,
    AppAuthedClubSlugDrillsNewRoute: AppAuthedClubSlugDrillsNewRoute,
    AppAuthedClubSlugGamesNewRoute: AppAuthedClubSlugGamesNewRoute,
    AppAuthedClubSlugInvitePrintRoute: AppAuthedClubSlugInvitePrintRoute,
    AppAuthedClubSlugLiveLiveIdRoute: AppAuthedClubSlugLiveLiveIdRoute,
    AppAuthedClubSlugMeSettingsRoute: AppAuthedClubSlugMeSettingsRoute,
    AppAuthedClubSlugRankingDailyRoute: AppAuthedClubSlugRankingDailyRoute,
    AppAuthedClubSlugTablesTableIdRoute: AppAuthedClubSlugTablesTableIdRoute,
    AppAuthedClubSlugTournamentsTournamentIdRoute:
      AppAuthedClubSlugTournamentsTournamentIdRoute,
    AppAuthedClubSlugDrillsIndexRoute: AppAuthedClubSlugDrillsIndexRoute,
    AppAuthedClubSlugGamesIndexRoute: AppAuthedClubSlugGamesIndexRoute,
    AppAuthedClubSlugMeIndexRoute: AppAuthedClubSlugMeIndexRoute,
    AppAuthedClubSlugPlayersIndexRoute: AppAuthedClubSlugPlayersIndexRoute,
    AppAuthedClubSlugRankingIndexRoute: AppAuthedClubSlugRankingIndexRoute,
    AppAuthedClubSlugTablesIndexRoute: AppAuthedClubSlugTablesIndexRoute,
    AppAuthedClubSlugTournamentsIndexRoute:
      AppAuthedClubSlugTournamentsIndexRoute,
    AppAuthedClubSlugDrillsDrillIdEditRoute:
      AppAuthedClubSlugDrillsDrillIdEditRoute,
    AppAuthedClubSlugGamesGameIdEditRoute:
      AppAuthedClubSlugGamesGameIdEditRoute,
    AppAuthedClubSlugMeTrainingPlanRoute: AppAuthedClubSlugMeTrainingPlanRoute,
    AppAuthedClubSlugPlayersPlayerIdSettingsRoute:
      AppAuthedClubSlugPlayersPlayerIdSettingsRoute,
    AppAuthedClubSlugDrillsDrillIdIndexRoute:
      AppAuthedClubSlugDrillsDrillIdIndexRoute,
    AppAuthedClubSlugGamesGameIdIndexRoute:
      AppAuthedClubSlugGamesGameIdIndexRoute,
    AppAuthedClubSlugMeTrainingIndexRoute:
      AppAuthedClubSlugMeTrainingIndexRoute,
    AppAuthedClubSlugPlayersPlayerIdIndexRoute:
      AppAuthedClubSlugPlayersPlayerIdIndexRoute,
    AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute:
      AppAuthedClubSlugPlayersPlayerIdTrainingPlanRoute,
    AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute:
      AppAuthedClubSlugPlayersPlayerIdTrainingIndexRoute,
  }

const AppAuthedClubSlugRouteRouteWithChildren =
  AppAuthedClubSlugRouteRoute._addFileChildren(
    AppAuthedClubSlugRouteRouteChildren,
  )

interface AppAuthedRouteRouteChildren {
  AppAuthedClubSlugRouteRoute: typeof AppAuthedClubSlugRouteRouteWithChildren
  AppAuthedOpsRoute: typeof AppAuthedOpsRoute
  AppAuthedSelectClubRoute: typeof AppAuthedSelectClubRoute
  AppAuthedUpdatePasswordRoute: typeof AppAuthedUpdatePasswordRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedClubsNoneRoute: typeof AppAuthedClubsNoneRoute
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedClubSlugRouteRoute: AppAuthedClubSlugRouteRouteWithChildren,
  AppAuthedOpsRoute: AppAuthedOpsRoute,
  AppAuthedSelectClubRoute: AppAuthedSelectClubRoute,
  AppAuthedUpdatePasswordRoute: AppAuthedUpdatePasswordRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedClubsNoneRoute: AppAuthedClubsNoneRoute,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppPairRoute: typeof AppPairRoute
  AppClubSlugManifestDotwebmanifestRoute: typeof AppClubSlugManifestDotwebmanifestRoute
  AppJoinSlugRoute: typeof AppJoinSlugRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppPairRoute: AppPairRoute,
  AppClubSlugManifestDotwebmanifestRoute:
    AppClubSlugManifestDotwebmanifestRoute,
  AppJoinSlugRoute: AppJoinSlugRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiClubsSlugLogoRoute: ApiClubsSlugLogoRoute,
  ApiOgClubsSlugRoute: ApiOgClubsSlugRoute,
  ApiOgGamesSplatRoute: ApiOgGamesSplatRoute,
  ApiOgPlayersSplatRoute: ApiOgPlayersSplatRoute,
  ApiOgTournamentsSplatRoute: ApiOgTournamentsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
